INSERT INTO resources (category, resourcename, resource_url) VALUES ('housing','The Community Service Society: Rental Assistance, Financial Support, Healthcare Navigation/Enrollment','http://www.cssny.org/programs');
INSERT INTO resources (category, resourcename, resource_url) VALUES ('legal','The Next Door Project at the Community Service Society: Rap Sheet Review and Repair, Legal Services 25+','http://www.cssny.org/programs/entry/the-next-door-project');
INSERT INTO resources (category, resourcename, resource_url) VALUES ('legal','Youth Represent: Legal Services 24 and under','http://youthrepresent.org/services/');
INSERT INTO resources (category, resourcename, resource_url) VALUES ('legal','Urban Justice Center: Legal Services','https://www.urbanjustice.org/');
INSERT INTO resources (category, resourcename, resource_url) VALUES ('legal','LegalAid: Legal Services- Immigration Services ','http://www1.nyc.gov/site/dycd/services/immigration.page');
INSERT INTO resources (category, resourcename, resource_url) VALUES ('legal','http://www1.nyc.gov/site/dycd/services/immigration.page','http://www1.cuny.edu/sites/citizenship-now/');
INSERT INTO case_conferences (swid, studid, todaysdate, strengths, challenges, challenge_steps, help, pershcolas_support, interest_outside, ifyes_what, follow_ups, fu_student, fu_perscholas, final_notes) VALUES (1, 3, '2017-11-20', 'strengths and proudest successes go here', 'biggest challenges go here', 'concrete steps you have taken to address those challenges go here', 'who do you go to for help/support & how will you utilize this help/support', 'how can per scholas support your success in our course and beyond', 'are you interested in any outside referrals/suppot', 'if yes, what goes here', 'dates and follow up notes go here', 'student follow up goes here', 'per scholas follow ups go here', 'final notes go here');
INSERT INTO case_conferences (swid, studid, todaysdate, strengths, challenges, challenge_steps, help, pershcolas_support, interest_outside, ifyes_what, follow_ups, fu_student, fu_perscholas, final_notes) VALUES (2, 2, '2017-10-23', 'strengths and proudest successes go here', 'biggest challenges go here', 'concrete steps you have taken to address those challenges go here', 'who do you go to for help/support & how will you utilize this help/support', 'how can per scholas support your success in our course and beyond', 'are you interested in any outside referrals/suppot', 'if yes, what goes here', 'dates and follow up notes go here', 'student follow up goes here', 'per scholas follow ups go here', 'final notes go here');
INSERT INTO case_conferences (swid, studid, todaysdate, strengths, challenges, challenge_steps, help, pershcolas_support, interest_outside, ifyes_what, follow_ups, fu_student, fu_perscholas, final_notes) VALUES (3, 1, '2017-09-05', 'strengths and proudest successes go here', 'biggest challenges go here', 'concrete steps you have taken to address those challenges go here', 'who do you go to for help/support & how will you utilize this help/support', 'how can per scholas support your success in our course and beyond', 'are you interested in any outside referrals/suppot', 'if yes, what goes here', 'dates and follow up notes go here', 'student follow up goes here', 'per scholas follow ups go here', 'final notes go here');
